# docker-compose.yml
version: "3"
services:
  db:
    container_name: sports_tournament_db
    image: postgres:11.5
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres